import { Adjustment } from '../../@types/adjustments/adjustmentsTypes'
import {
  Charge,
  ChargeRemand,
  IntersectingSentence,
  LegacyDataProblem,
  RemandResult,
} from '../../@types/identifyRemandPeriods/identifyRemandPeriodsTypes'

const remandResult = {
  charges: {
    3333: {
      chargeId: 3333,
      offence: { code: 'TP47017', statute: 'TP47', description: 'A sentence charge, way before the remand dates' },
      offenceDate: '2023-02-01',
      bookingId: 1204935,
      bookNumber: '41938A',
      offenceEndDate: null,
      sentenceSequence: 88,
      sentenceDate: '2000-03-21',
      courtCaseRef: 'CASE5678',
      courtLocation: 'Birmingham Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: true,
    } as Charge,
    3933924: {
      chargeId: 3933924,
      offence: { code: 'TP47017', statute: 'TP47', description: 'Accidentally allow a chimney to be on fire' },
      offenceDate: '2023-02-01',
      bookingId: 1204935,
      bookNumber: '41938A',
      offenceEndDate: null,
      sentenceSequence: null,
      sentenceDate: null,
      courtCaseRef: 'CASE5678',
      courtLocation: 'Birmingham Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: true,
    } as Charge,
    3933870: {
      chargeId: 3933870,
      offence: { code: 'WR91001', statute: 'WR91', description: 'Abstract water without a licence' },
      offenceDate: '2022-01-10',
      bookingId: 1204935,
      bookNumber: '41938A',
      offenceEndDate: null,
      sentenceSequence: 1,
      sentenceDate: '2023-03-21',
      courtCaseRef: 'CASE1234',
      courtLocation: 'Birmingham Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: true,
    } as Charge,
    2222: {
      chargeId: 2222,
      offence: { code: 'WR91001', statute: 'WR91', description: 'Abstract water without a licence' },
      offenceDate: '2022-01-10',
      bookingId: 1204940,
      bookNumber: '41938A',
      offenceEndDate: null,
      sentenceSequence: 1,
      sentenceDate: '2023-03-21',
      courtCaseRef: 'CASE1234',
      courtLocation: 'Birmingham Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: true,
    } as Charge,
    4444: {
      chargeId: 4444,
      offence: { code: 'WR91001', statute: 'WR91', description: 'offence on another booking' },
      offenceDate: '2022-01-10',
      bookingId: 1204936,
      bookNumber: '41938A',
      offenceEndDate: null,
      sentenceSequence: 1,
      sentenceDate: '2023-03-21',
      courtCaseRef: 'CASE1234',
      courtLocation: 'Birmingham Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: true,
    } as Charge,
    3934217: {
      chargeId: 3934217,
      offence: { code: 'TH68036', statute: 'TH68', description: 'Burglary dwelling and theft  - no violence' },
      offenceDate: '2022-06-18',
      bookingId: 1209333,
      bookNumber: '46201A',
      offenceEndDate: null,
      sentenceSequence: 3,
      sentenceDate: '2022-08-17',
      courtCaseRef: null,
      courtLocation: 'Wood Green Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: true,
    } as Charge,
    3934220: {
      chargeId: 3934220,
      offence: { code: 'COML016', statute: 'COML', description: 'Escape from lawful custody' },
      offenceDate: '2021-06-18',
      bookingId: 1209333,
      bookNumber: '46201A',
      offenceEndDate: null,
      sentenceSequence: 6,
      sentenceDate: '2022-08-17',
      courtCaseRef: null,
      courtLocation: 'Wood Green Crown Court',
      resultDescription: 'Recall to Prison',
      isInconclusive: true,
    } as Charge,
    3934221: {
      chargeId: 3934221,
      offence: { code: 'COML016', statute: 'COML', description: 'Escape from lawful custody' },
      offenceDate: '2021-06-18',
      bookingId: 1209333,
      bookNumber: '46201X',
      offenceEndDate: null,
      sentenceSequence: 6,
      sentenceDate: '2022-08-17',
      courtCaseRef: null,
      courtLocation: 'Wood Green Crown Court',
      resultDescription: 'Recall to Prison',
      isInconclusive: true,
    } as Charge,
  },
  adjustments: [
    {
      fromDate: '2023-01-10',
      toDate: '2023-01-20',
      remand: {
        chargeId: [3933870],
      },
      days: 11,
      status: 'ACTIVE',
    } as Adjustment,
  ],
  intersectingSentencesUsingHistoricCalculation: [],
  chargeRemand: [
    {
      from: '2022-11-23',
      to: '2022-12-15',
      days: 23,
      chargeIds: [3933924],
      status: 'CASE_NOT_CONCLUDED',
    } as ChargeRemand,
    {
      from: '2021-11-23',
      to: '2021-12-15',
      days: 23,
      chargeIds: [3933924],
      status: 'CASE_NOT_CONCLUDED',
    } as ChargeRemand,
    {
      from: '2023-01-10',
      to: '2023-01-20',
      days: 11,
      chargeIds: [3933870],
      status: 'APPLICABLE',
    } as ChargeRemand,
    {
      from: '2023-02-01',
      to: '2023-03-20',
      days: 48,
      chargeIds: [3933870],
      status: 'APPLICABLE',
    } as ChargeRemand,

    {
      from: '2023-02-01',
      to: '2023-03-20',
      chargeIds: [2222],
      days: 48,
      status: 'SHARED',
    } as ChargeRemand,
  ],
  intersectingSentences: [
    {
      from: '2022-08-17',
      to: '2023-01-16',
      sentence: { sequence: 3, sentenceDate: '2022-08-17', recallDate: null, bookingId: 1209333, recallDates: [] },
      chargeId: 3934217,
      days: 92,
      service: 'HISTORIC',
      errors: [],
      calculationIds: [1],
    } as IntersectingSentence,
    {
      from: '2023-01-17',
      to: '2023-01-18',
      sentence: {
        sequence: 6,
        sentenceDate: '2022-08-17',
        recallDate: '2023-05-18',
        bookingId: 1209333,
        recallDates: [],
      },
      chargeId: 3934220,
      days: 140,
      service: 'HISTORIC',
      errors: [],
      calculationIds: [1],
    } as IntersectingSentence,
    {
      // Same book number and shorter, shouldn't be displayed
      from: '2023-01-17',
      to: '2023-01-18',
      sentence: {
        sequence: 6,
        sentenceDate: '2022-08-17',
        recallDate: '2023-05-18',
        bookingId: 1209333,
        recallDates: [],
      },
      chargeId: 3934220,
      days: 140,
      service: 'HISTORIC',
      errors: [],
      calculationIds: [1],
    } as IntersectingSentence,
    {
      // Different book number should be displayed with text.
      from: '2023-01-17',
      to: '2023-01-18',
      sentence: {
        sequence: 6,
        sentenceDate: '2022-08-17',
        recallDate: '2023-05-18',
        bookingId: 1209333,
        recallDates: [],
      },
      chargeId: 3934221,
      days: 140,
      service: 'HISTORIC',
      errors: [],
      calculationIds: [1],
    } as IntersectingSentence,
    {
      // After most recent adjustment
      from: '2022-08-17',
      to: '2023-01-16',
      sentence: { sequence: 3, sentenceDate: '2022-08-17', recallDate: null, bookingId: 1209333, recallDates: [] },
      chargeId: 3934217,
      days: 92,
      service: 'HISTORIC',
      errors: [],
      calculationIds: [1],
    } as IntersectingSentence,
  ],
  periodsServingSentenceUsingCRDS: [],
  issuesWithLegacyData: [
    {
      message: 'This is an important message',
      offence: { code: 'ASD', statute: 'WR91', description: 'An offence with same statute' },
      bookingId: 1204935,
      bookNumber: '41938A',
      courtCaseRef: 'CASE5678',
    } as LegacyDataProblem,
    {
      message: 'This is also important message',
      offence: { code: 'A', statute: 'B', description: 'C' },
      bookingId: 1204935,
      bookNumber: '41938A',
      courtCaseRef: 'CASE1234',
    } as LegacyDataProblem,
    {
      message: 'This is not an important message',
      offence: { code: 'TP47017', statute: 'TP47', description: 'Accidentally allow a chimney to be on fire' },
      bookingId: 1204935,
      bookNumber: '41938A',
      courtCaseRef: 'CASE5678',
    } as LegacyDataProblem,
  ],
  periodsOutOfPrison: [],
} as RemandResult

const conclusiveRemandResult = {
  charges: {
    1001: {
      chargeId: 1001,
      offence: {
        code: 'AB12345',
        statute: 'AB12',
        description: 'Theft from a vehicle',
      },
      offenceDate: '2023-05-01',
      bookingId: 999999,
      bookNumber: '12345A',
      offenceEndDate: null,
      sentenceSequence: 1,
      sentenceDate: '2023-06-01',
      courtCaseRef: 'CASE1001',
      courtLocation: 'Manchester Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: false,
    } as Charge,
  },
  adjustments: [
    {
      fromDate: '2023-05-10',
      toDate: '2023-05-20',
      remand: {
        chargeId: [1001],
      },
      days: 0,
      status: 'ACTIVE',
    } as Adjustment,
  ],
  intersectingSentencesUsingHistoricCalculation: [],
  chargeRemand: [
    {
      from: '2023-05-10',
      to: '2023-05-20',
      days: 11,
      chargeIds: [1001],
      status: 'NOT_SENTENCED',
    } as ChargeRemand,
  ],
  intersectingSentences: [
    {
      from: '2023-06-01',
      to: '2023-12-01',
      sentence: {
        sequence: 1,
        sentenceDate: '2023-06-01',
        recallDate: null,
        bookingId: 999999,
        recallDates: [],
      },
      chargeId: 1001,
      days: 184,
      service: 'HISTORIC',
      errors: [],
      calculationIds: [101],
    } as IntersectingSentence,
  ],
  periodsServingSentenceUsingCRDS: [],
  issuesWithLegacyData: [],
  periodsOutOfPrison: [],
} as RemandResult

const onePlusremandDaysRemandResult = {
  charges: {
    1001: {
      chargeId: 1001,
      offence: {
        code: 'AB12345',
        statute: 'AB12',
        description: 'Theft from a vehicle',
      },
      offenceDate: '2023-05-01',
      bookingId: 999999,
      bookNumber: '12345A',
      offenceEndDate: null,
      sentenceSequence: 1,
      sentenceDate: '2023-06-01',
      courtCaseRef: 'CASE1001',
      courtLocation: 'Manchester Crown Court',
      resultDescription: 'Imprisonment',
      isInconclusive: false,
    } as Charge,
  },
  adjustments: [
    {
      fromDate: '2023-05-10',
      toDate: '2023-05-20',
      remand: {
        chargeId: [1001],
      },
      days: 10,
      status: 'ACTIVE',
    } as Adjustment,
  ],
  intersectingSentencesUsingHistoricCalculation: [],
  chargeRemand: [
    {
      from: '2023-05-10',
      to: '2023-05-20',
      days: 11,
      chargeIds: [1001],
      status: 'NOT_SENTENCED',
    } as ChargeRemand,
  ],
  intersectingSentences: [
    {
      from: '2023-06-01',
      to: '2023-12-01',
      sentence: {
        sequence: 1,
        sentenceDate: '2023-06-01',
        recallDate: null,
        bookingId: 999999,
        recallDates: [],
      },
      chargeId: 1001,
      days: 184,
      service: 'HISTORIC',
      errors: [],
      calculationIds: [101],
    } as IntersectingSentence,
  ],
  periodsServingSentenceUsingCRDS: [],
  issuesWithLegacyData: [],
  periodsOutOfPrison: [],
} as RemandResult

export default conclusiveRemandResult

export { remandResult, conclusiveRemandResult, onePlusremandDaysRemandResult }
