/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/relevant-remand/{prisonerId}': {
    /**
     * Calculates relevant remand
     * @description This endpoint will calculate relevant remand based on the data from NOMIS before returning it to the user
     */
    post: operations['calculate']
  }
  '/relevant-remand/{prisonerId}/decision': {
    /**
     * Get the latest decision for a given person
     * @description This endpoint return the latest decision for a given person.
     */
    get: operations['getDecision']
    /**
     * Saves a decision to accept or reject relevant remand
     * @description This endpoint will save a decision to accept or reject relevant remand, and also call the adjustments api to save the data.
     */
    post: operations['saveDecision']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    Charge: {
      /** Format: int64 */
      chargeId: number
      offence: components['schemas']['Offence']
      /** Format: date */
      offenceDate: string
      /** Format: int64 */
      bookingId: number
      /** Format: date */
      offenceEndDate?: string
      /** Format: int32 */
      sentenceSequence?: number
      /** Format: date */
      sentenceDate?: string
      courtCaseRef?: string
      courtLocation?: string
      resultDescription?: string
    }
    Offence: {
      code: string
      statute: string
      description: string
    }
    Remand: {
      /** Format: date */
      from: string
      /** Format: date */
      to: string
      charge: components['schemas']['Charge']
      /** Format: int64 */
      days?: number
    }
    RemandResult: {
      chargeRemand: components['schemas']['Remand'][]
      sentenceRemand: components['schemas']['Remand'][]
      intersectingSentences: components['schemas']['SentencePeriod'][]
      issuesWithLegacyData: string[]
    }
    Sentence: {
      /** Format: int32 */
      sequence: number
      /** Format: date */
      sentenceDate: string
      /** Format: date */
      recallDate?: string
      /** Format: int64 */
      bookingId: number
    }
    SentencePeriod: {
      /** Format: date */
      from: string
      /** Format: date */
      to: string
      sentence: components['schemas']['Sentence']
      /** Format: int64 */
      days?: number
    }
    IdentifyRemandDecisionDto: {
      accepted: boolean
      rejectComment?: string
      /** Format: int32 */
      days?: number
      /** Format: date-time */
      decisionOn?: string
      decisionBy?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  /**
   * Calculates relevant remand
   * @description This endpoint will calculate relevant remand based on the data from NOMIS before returning it to the user
   */
  calculate: {
    parameters: {
      path: {
        /**
         * @description The prisoners ID (aka nomsId)
         * @example A1234AB
         */
        prisonerId: string
      }
    }
    responses: {
      /** @description Returns calculated relevant remand */
      200: {
        content: {
          'application/json': components['schemas']['RemandResult']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['RemandResult']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['RemandResult']
        }
      }
    }
  }
  /**
   * Get the latest decision for a given person
   * @description This endpoint return the latest decision for a given person.
   */
  getDecision: {
    parameters: {
      path: {
        /**
         * @description The prisoners ID (aka nomsId)
         * @example A1234AB
         */
        prisonerId: string
      }
    }
    responses: {
      /** @description Gets latest remand decision for person. */
      200: {
        content: {
          'application/json': components['schemas']['IdentifyRemandDecisionDto']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['IdentifyRemandDecisionDto']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['IdentifyRemandDecisionDto']
        }
      }
    }
  }
  /**
   * Saves a decision to accept or reject relevant remand
   * @description This endpoint will save a decision to accept or reject relevant remand, and also call the adjustments api to save the data.
   */
  saveDecision: {
    parameters: {
      path: {
        /**
         * @description The prisoners ID (aka nomsId)
         * @example A1234AB
         */
        prisonerId: string
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IdentifyRemandDecisionDto']
      }
    }
    responses: {
      /** @description Decision created okay. */
      201: never
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: never
      /** @description Forbidden, requires an appropriate role */
      403: never
    }
  }
}
