#!/bin/sh
set -e

# Load nvm (adjust path if needed)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Use desired node version (optional)
nvm use

# Run tasks
NODE_ENV=dev
npx lint-staged
npm run typecheck
npm test